### ISSUE TITLE
Project goal

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-bencode-online#1]
This project aims to build a web app to convert from Bencode format to JSON.

The project will be very similar to https://github.com/Chocobo1/bencode_online

### Features

- Simple website where users can paste or upload a bencoded value and convert it to JSON.
- The site will be hosted on GitHub Pages
- The conversion will be done using these Rust crates:
  - https://github.com/torrust/bencode2json
  - https://github.com/torrust/json2bencode
- There will not be a banked service. It will be a static website using the Rust crates via WebAssembly (WASM).

### Proposal

To set up this project, here’s an outline:

1. Set Up Rust with WASM Target:

Install the WASM target for Rust if you haven't already: rustup target add wasm32-unknown-unknown.
Use a framework like wasm-bindgen or wasm-pack to compile your Rust crate to WebAssembly, exposing the Bencode-to-JSON conversion functions.

2. Create the Frontend:

For a static website, consider using a minimal HTML/CSS/JavaScript framework or a frontend framework like Svelte, which you can compile to static files.
Set up a simple form where users can either paste the bencoded text or upload a file.

3. WASM Integration:

Write JavaScript functions to call the compiled WebAssembly functions for the Bencode-to-JSON conversion.
Use the wasm-bindgen JavaScript interop library to handle inputs and outputs between the WebAssembly and JavaScript.

4. Deployment:

Use GitHub Actions to automate deployment to GitHub Pages. A common workflow is to build the Rust project and push the compiled WebAssembly and static files to a gh-pages branch.

5. Example Workflow:

Create a GitHub Actions workflow in .github/workflows/deploy.yml that builds the Rust code to WebAssembly, compiles the frontend, and deploys to GitHub Pages.

### Project Structure (proposal)

```text
torrust-bencode-online/
├── .github/
│   └── workflows/
│       └── deploy.yml        # GitHub Actions workflow for automatic deployment
├── src/
│   ├── lib.rs                # Main Rust source file containing conversion logic
│   └── utils.rs              # Utility functions for the Rust crate (optional, for modularity)
├── static/                   # Static files for the website
│   ├── index.html            # Main HTML file
│   └── main.js               # JavaScript file to interact with WASM
├── Cargo.toml                # Rust dependencies and project metadata
├── package.json              # For wasm-pack, used to handle JS dependencies
└── README.md                 # Project description and usage instructions
```

### Files (proposal)

Generated by ChatGPT only as a starting point. I have not tested it.

`Cargo.toml`:

```toml
[package]
name = "bencode_to_json_converter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.bencode]  # Assuming bencode is a crate that helps parse bencoded data
version = "0.1" 

[profile.release]
opt-level = "s"
```

`src/lib.rs`

```rust
use wasm_bindgen::prelude::*;
use bencode::de::from_str;
use serde_json::json;

#[wasm_bindgen]
pub fn convert_bencode_to_json(bencode_str: &str) -> Result<String, JsValue> {
    match from_str(bencode_str) {
        Ok(parsed) => Ok(json!(parsed).to_string()),
        Err(err) => Err(JsValue::from_str(&format!("Failed to parse: {}", err))),
    }
}
```

`static/index.html`

```thml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bencode to JSON Converter</title>
</head>
<body>
    <h1>Bencode to JSON Converter</h1>
    <textarea id="bencode-input" rows="10" cols="50" placeholder="Paste bencoded data here..."></textarea><br>
    <button id="convert-btn">Convert</button>
    <h2>JSON Output</h2>
    <pre id="json-output"></pre>
    <script type="module" src="main.js"></script>
</body>
</html>
```

`static/main.js`

```javascript
import init, { convert_bencode_to_json } from '../pkg/bencode_to_json_converter.js';

async function run() {
    await init();

    document.getElementById("convert-btn").addEventListener("click", () => {
        const bencodeInput = document.getElementById("bencode-input").value;
        try {
            const jsonOutput = convert_bencode_to_json(bencodeInput);
            document.getElementById("json-output").textContent = jsonOutput;
        } catch (e) {
            document.getElementById("json-output").textContent = "Error: " + e;
        }
    });
}

run();
```

`.github/workflows/deploy.yml`

```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build WASM
      run: wasm-pack build --release --target web --out-dir ./static/pkg

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static
```

`package.json`

```json
{
  "name": "bencode_to_json_converter",
  "version": "1.0.0",
  "scripts": {
    "start": "serve static"
  },
  "devDependencies": {
    "serve": "^11.3.2"
  }
}
```
